"""add notification_preferences to users

Revision ID: 4c83d7dc335a
Revises: d6b24ae95a98
Create Date: 2026-06-30 11:05:26.290504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c83d7dc335a'
down_revision = 'd6b24ae95a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_calendar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('show_public_holidays', sa.Boolean(), nullable=False),
    sa.Column('show_school_vacations', sa.Boolean(), nullable=False),
    sa.Column('school_vacation_zone', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')

    op.drop_table('restaurant_calendar_settings')
    # ### end Alembic commands ###
