"""catalog-entity-replace-text-items

Revision ID: bfb39474c140
Revises: 55b3b63a2e51
Create Date: 2026-05-21 19:20:13.281740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfb39474c140'
down_revision = '55b3b63a2e51'
branch_labels = None
depends_on = None


def upgrade():
    # ── Étape 0 : supprimer les données liées à l'ancienne architecture ──────
    # Suppression dans l'ordre des dépendances FK
    op.execute("DELETE FROM menu_item_images")
    op.execute("DELETE FROM menu_item_certifications")
    op.execute("DELETE FROM menu_item_dietary_tags")
    op.execute("DELETE FROM menu_items")
    op.execute("DELETE FROM gallery_image_tags")
    op.execute("DELETE FROM gallery_images")
    # ────────────────────────────────────────────────────────────────────────

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dish_catalog', schema=None) as batch_op:
        batch_op.create_index('ix_dish_catalog_category', ['category_id'], unique=False)
        batch_op.create_index('ix_dish_catalog_restaurant', ['restaurant_id'], unique=False)

    op.create_table('category_substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'dish_id', name='uq_cat_sub_dish')
    )
    with op.batch_alter_table('category_substitutions', schema=None) as batch_op:
        batch_op.create_index('ix_category_substitutions_cat', ['category_id'], unique=False)

    op.create_table('dish_certifications',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('certification_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'certification_id')
    )
    op.create_table('dish_dietary_tags',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['dietary_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'tag_id')
    )
    op.drop_table('menu_item_certifications')
    op.drop_table('menu_item_dietary_tags')
    with op.batch_alter_table('menu_item_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_images_gallery'))
        batch_op.drop_index(batch_op.f('ix_menu_item_images_item'))

    op.drop_table('menu_item_images')
    with op.batch_alter_table('gallery_image_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_image_tags_name'))
        batch_op.drop_index(batch_op.f('ix_gallery_image_tags_type'))

    op.drop_table('gallery_image_tags')
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_images_restaurant'))

    op.drop_table('gallery_images')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'dish_catalog', ['dish_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('name')
        batch_op.drop_column('replacement_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replacement_label', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        # FK créée sans nom explicite dans upgrade() → nom par défaut PostgreSQL
        batch_op.drop_constraint('menu_items_dish_id_fkey', type_='foreignkey')
        batch_op.drop_column('dish_id')

    op.create_table('gallery_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uploaded_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('gallery_images_restaurant_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('gallery_images_uploaded_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gallery_images_pkey'))
    )
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_images_restaurant'), ['restaurant_id'], unique=False)

    op.create_table('gallery_image_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gallery_image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tag_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gallery_image_id'], ['gallery_images.id'], name=op.f('gallery_image_tags_gallery_image_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gallery_image_tags_pkey'))
    )
    with op.batch_alter_table('gallery_image_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_image_tags_type'), ['tag_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_image_tags_name'), ['name'], unique=False)

    op.create_table('menu_item_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gallery_image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gallery_image_id'], ['gallery_images.id'], name=op.f('menu_item_images_gallery_image_id_fkey')),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('menu_item_images_menu_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('menu_item_images_pkey'))
    )
    with op.batch_alter_table('menu_item_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_images_item'), ['menu_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_images_gallery'), ['gallery_image_id'], unique=False)

    op.create_table('menu_item_dietary_tags',
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('menu_item_dietary_tags_menu_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['dietary_tags.id'], name=op.f('menu_item_dietary_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'tag_id', name=op.f('menu_item_dietary_tags_pkey'))
    )
    op.create_table('menu_item_certifications',
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certification_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], name=op.f('menu_item_certifications_certification_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('menu_item_certifications_menu_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'certification_id', name=op.f('menu_item_certifications_pkey'))
    )
    op.drop_table('dish_dietary_tags')
    op.drop_table('dish_certifications')
    with op.batch_alter_table('category_substitutions', schema=None) as batch_op:
        batch_op.drop_index('ix_category_substitutions_cat')

    op.drop_table('category_substitutions')
    with op.batch_alter_table('dish_catalog', schema=None) as batch_op:
        batch_op.drop_index('ix_dish_catalog_restaurant')
        batch_op.drop_index('ix_dish_catalog_category')

    op.drop_table('dish_catalog')
    # ### end Alembic commands ###
