"""add menu_id to category_substitutions

Revision ID: d6b24ae95a98
Revises: ec0cf6a02893
Create Date: 2026-06-24 08:15:06.737631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6b24ae95a98'
down_revision = 'ec0cf6a02893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_substitutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_category_substitutions_cat'))
        batch_op.drop_constraint(batch_op.f('uq_cat_sub_dish'), type_='unique')
        batch_op.create_index('ix_cat_sub_cat', ['category_id'], unique=False)
        batch_op.create_index('ix_cat_sub_menu', ['menu_id'], unique=False)
        batch_op.create_unique_constraint('uq_menu_cat_sub_dish', ['menu_id', 'category_id', 'dish_id'])
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_substitutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        # FK créée sans nom explicite dans upgrade() → nom par défaut PostgreSQL
        batch_op.drop_constraint('category_substitutions_menu_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('uq_menu_cat_sub_dish', type_='unique')
        batch_op.drop_index('ix_cat_sub_menu')
        batch_op.drop_index('ix_cat_sub_cat')
        batch_op.create_unique_constraint(batch_op.f('uq_cat_sub_dish'), ['category_id', 'dish_id'])
        batch_op.create_index(batch_op.f('ix_category_substitutions_cat'), ['category_id'], unique=False)
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
