"""add inbox_notifications table

Revision ID: ec0cf6a02893
Revises: bfb39474c140
Create Date: 2026-06-22 22:12:45.453247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0cf6a02893'
down_revision = 'bfb39474c140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_notifications_restaurant_id'), ['restaurant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbox_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('inbox_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_inbox_notifications_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_inbox_notifications_created_at'))

    op.drop_table('inbox_notifications')
    # ### end Alembic commands ###
