"""add passkeys table

Revision ID: ff7caab46c56
Revises: b3c4d5e6f7a9
Create Date: 2026-03-21 17:47:51.048791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7caab46c56'
down_revision = 'b3c4d5e6f7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passkeys_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('event_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_images_event_id'))
        batch_op.drop_constraint(batch_op.f('event_images_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    with op.batch_alter_table('menu_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_images_menu_id'))
        batch_op.drop_constraint(batch_op.f('menu_images_menu_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'])

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_restaurant_today'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_restaurant_tomorrow'))

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('tags_customized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('tags_customized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_restaurant_tomorrow'), ['restaurant_id', 'notify_tomorrow_menu', 'notify_tomorrow_menu_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_restaurant_today'), ['restaurant_id', 'notify_today_menu', 'notify_today_menu_time'], unique=False)

    with op.batch_alter_table('menu_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('menu_images_menu_id_fkey'), 'menus', ['menu_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_menu_images_menu_id'), ['menu_id'], unique=False)

    with op.batch_alter_table('event_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_images_event_id_fkey'), 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_event_images_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('passkeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passkeys_user_id'))

    op.drop_table('passkeys')
    # ### end Alembic commands ###
